### ISSUE TITLE
[Bug report] eval_point is True

### ISSUE THREAD

**Issue by CM-BF** [yuan-yin/CoDA#1]
Hi yuan-yin,

Thank you for your great work! I noticed an issue when I ran the code, and hope to get clarified.

In the [ode_model.py line 87](https://github.com/yuan-yin/CoDA/blob/cc89faf0e48a939682b67abbd7e6379b9ce8887d/ode_model.py#L87), the condition `eval_point is True` always returns `False` regardless of the value (True/False) of `eval_point`. Is this normal? Will it affect the final result if I change the condition into `eval_point == True`?

Thank you for your assistance in advance!

Best regards,
Shurui

**Comment by yuan-yin** [comment]
Hi Shurui,

Thank you for your interest in our work. If you look at [L81](https://github.com/yuan-yin/CoDA/blob/cc89faf0e48a939682b67abbd7e6379b9ce8887d/ode_model.py#L81C13-L81C61), the `eval_points` are indeed generated, so it is not always `True`. Even though it's highly probable to be `True` at the beginning of training due to an `epsilon` around 1, as the `epsilon` decreases, the behavior will change.

Hope this helps you.

Best regards,
Yuan

**Comment by CM-BF** [comment]
Hi Yuan,

Thank you for your prompt response! What I mean was that the condition `eval_point is True` cannot work properly. Even when `eval_point == True`, `eval_point is True` will return `False`. This behavior leads to that the code between line 88 and line 95 will never be executed.

Best regards,
Shurui

**Comment by yuan-yin** [comment]
Ah ok, sorry I didn't well understand the question. It's quite curious because when we originally wrote this code, it worked fine. Perhaps there have been some changes in the behavior of NumPy or Python. If changing to `==` works for you, feel free to proceed, and I'll investigate it further.

**Comment by yuan-yin** [comment]
I am pretty sure right now that there was a behavior change in NumPy for the default boolean type. It seems that it was the same as Python's built-in `bool` but now it's no longer the case. I will correct this. Thank you for your report.

**Comment by CM-BF** [comment]
That is interesting. Thank you for your updates. : )
